name:                StackProject
version:             0.1.0.0
github:              "githubuser/StackProject"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/StackProject#readme>

default-extensions: 
- RankNTypes
- TypeOperators
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- DeriveFunctor
- ScopedTypeVariables
- ViewPatterns
- QuantifiedConstraints
- StandaloneDeriving
- ConstraintKinds
- FunctionalDependencies
- GADTs
- UndecidableSuperClasses
- KindSignatures
- LambdaCase

dependencies:
- base >= 4.7 && < 5
- show-combinators
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  StackProject-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - StackProject

tests:
  StackProject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - StackProject
